name: Build Debug APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK command-line tools
        run: |
          # Use runner temp directory for SDK (persist via GITHUB_ENV for other steps)
          ANDROID_SDK_ROOT="$RUNNER_TEMP/android-sdk"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y unzip wget ca-certificates
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"

          # Try download with retries and follow redirects
          ZIP_URL="https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip"
          MAX_TRIES=5
          i=0
          while [ $i -lt $MAX_TRIES ]; do
            i=$((i+1))
            echo "Downloading commandline tools (attempt $i/$MAX_TRIES)..."
            wget -q --show-progress --tries=3 --timeout=30 --no-check-certificate -O cmdline.zip "$ZIP_URL" && break
            echo "Download failed, retrying in 3s..."
            sleep 3
          done

          if [ ! -f cmdline.zip ]; then
            echo "ERROR: failed to download Android commandline tools after $MAX_TRIES attempts"
            ls -la
            exit 1
          fi

          unzip -o cmdline.zip -d cmdline-tools
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          mv cmdline-tools/* "$ANDROID_SDK_ROOT/cmdline-tools/latest" || true

          # Ensure sdkmanager is executable
          chmod +x "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/"* || true

          # Install basic SDK components (use --no_https as fallback)
          YES_CMD="yes |"
          if command -v yes >/dev/null 2>&1; then YES_CMD="yes |"; else YES_CMD="printf 'y\n' |"; fi

          if ! $YES_CMD "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-34" "build-tools;34.0.0"; then
            echo "sdkmanager https failed, retrying with --no_https"
            $YES_CMD "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --no_https --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          fi

          chmod -R a+rX "$ANDROID_SDK_ROOT"

      - name: Add Android tools to PATH
        run: |
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Build with Gradle (assembleDebug)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.4'
          arguments: 'assembleDebug'

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
